### ISSUE TITLE
AbstractBlock: make method getMainElement() public.

### ISSUE THREAD

**Issue by nankibykova** [WileyLabs/teasy#115]
I think it will be more useful to make method **getMainElement()** public. In current **protected** implementation I can not use this method from pages.

**Comment by vefimofff** [comment]
After some discussion, we decided to keep things as is. It's quite a good feature not-to make TeasyElement-returning methods as public (to prevent the direct use of them in tests classes). Instead, you may create a necessary method in your Block class that will take all necessary data from mainElement and return it to outer-world. Hope this help. Closing this issue for now.
