### ISSUE TITLE
Different exception text for identical methods: findElement(final By by) and for findElement(TeasyElement context, final By by)

### ISSUE THREAD

**Issue by dimazhiv** [WileyLabs/teasy#119]
for: `public WebElement findElement(final By by)` it is
            throw new NoSuchElementException("Unable to **find** element " + by + ", Exception - " + e);
      
and for:
    `public WebElement findElement(TeasyElement context, final By by) ` it is
            throw new NoSuchElementException("Unable to **locate** element " + by + ", Exception - " + e);
I suggest то leave one.

**Comment by vefimofff** [comment]
fixed by #120
