### ISSUE TITLE
Tests for element()

### ISSUE THREAD

**Issue by vefimofff** [WileyLabs/teasy#12]
Develop tests for method `element(final By locator)` from OurElementProvider.

Create .html file and tests running on this file to check that element() method works as expected. 
1. element returns *first visible* element using given locator
2. element waits for element to become visible (e.g. simulate situation when there is no element, then after 3 seconds it appears)
3. element fails if nothing is found. (exception is thrown)
4. there are 3 iframes and visible element is present in the second one.

Please feel free to add more tests on your taste.

**Comment by EreOo** [comment]
Hi, @vefimofff !
I want try do this isuue.

**Comment by vefimofff** [comment]
@EreOo cool, join our gitter chat https://gitter.im/teasy-test-framework/Lobby and lets discuss there.

**Comment by vefimofff** [comment]
Closing this as for the start point we have more that enough tests. The new tests to be added when we consider them necessary.
