### ISSUE TITLE
Convert OurWebElement to WebElement

### ISSUE THREAD

**Issue by skopanirov** [WileyLabs/teasy#14]
Hi all,

Is there any way to convert OurWebElement to classic WebElement?

There are some custom Selenium functions (Drag and Drop for example) that require WebElement as a parameter and as long as we have only OurWebElement, we can't use those functions.

**Comment by vefimofff** [comment]
@skopanirov good catch. I will add a method to return WebElement. However you know I think like we should consider adding methods like drag-n-drop to OurWebElement. Anyway I like the idea of adding a possibility to extract WebElement from OurWebElement.

**Comment by estuold** [comment]
ourWebElement.getWrappedWebElement() return classic selenium webElement

**Comment by vefimofff** [comment]
I see, great. totally missed that. @skopanirov nothing to do there then, there is everything you need ;)
