### ISSUE TITLE
element().should().haveAttribute() for CSS attributes.

### ISSUE THREAD

**Issue by dimazhiv** [WileyLabs/teasy#165]
Seems it would be useful if we were able to check CSS attribute through pattern like for simple element attributes: element().should().haveAttribute(nameAttribute, value)

For example:
element().should().haveCssAttribute(nameAttribute, expectedValue)
instead of using something like this:
 assertThat(element().getCssValue("nameAttribute")).isEqualTo(expectedColor);

**Comment by vefimofff** [comment]
duplicates https://github.com/WileyLabs/teasy/issues/77
