### ISSUE TITLE
java.lang.ClassCastException in longTap(OurWebElement webElement, int timeoutInMilSec)

### ISSUE THREAD

**Issue by FedVl** [WileyLabs/teasy#19]
I get java.lang.ClassCastException when trying to use longTap method for iOS testing.
See stack trace part below:
java.lang.ClassCastException: com.sun.proxy.$Proxy44 cannot be cast to org.openqa.selenium.internal.HasIdentity
	at io.appium.java_client.TouchAction.press(TouchAction.java:52)
	at com.wiley.wat.base.MobileBasePage.longTap(MobileBasePage.java:218)

**Comment by vefimofff** [comment]
@FedVl it would be very helpful if you provide a full stacktrace so we could see where exactly it fails in Teasy

**Comment by FedVl** [comment]
@vefimofff  - added new stack trace part.
