### ISSUE TITLE
public class NullTeasyElement throws NoSuchElementException without throwable.

### ISSUE THREAD

**Issue by FedVl** [WileyLabs/teasy#192]
public class NullTeasyElement throws NoSuchElementException without throwable.
It causes an error message with extra details ( support message, build information, system information, additional information) in the report but it shoud not because in fact the NoSuchElementException extends WebDriverException and should returns Throwable getMessage() method.
Possible solutions are:
1. Create a custom instance of Throwable and throw it in case when we don't need additional details in error message.
2. Update TeasyError class to handle such cases.

**Comment by vefimofff** [comment]
fixed in 2.0.4
