### ISSUE TITLE
No `master` branch?

### ISSUE THREAD

**Issue by BigBlueHat** [WileyLabs/teasy#2]
I was confused when I cloned this project as there was no `master` branch and consequently no files were put into my working copy. Upon visiting GitHub again I realized that there was a single `newway` branch. Guessing that's to keep it out of the way of the internal `master` branch?

It is possible to using the [Setting](https://github.com/WileyLabs/teasy/settings) to config `newway` as the default branch--which should making cloning more intuitive. However, it's still probably best to make this the `master` branch as soon as that's workable for all involved.

Cheers!
🎩

**Comment by estuold** [comment]
Branch `newway` was merged to `master`, `master` set as default.

**Comment by vefimofff** [comment]
@BigBlueHat thanks for opening this issue. You are absolutely right that newway was actually a master and of course it make sense to name it properly. As of now we have added master and will probably delete newway branch as it's not needed anymore.
