### ISSUE TITLE
Refresh workarounds for IE and Safari

### ISSUE THREAD

**Issue by vefimofff** [WileyLabs/teasy#3]
Currently there are plenty of workarounds for old IE and Safari testing which are most likely not actual any longer according to our latest experiments. They simply need to be removed. They can be found by constructions like

``` java
if(isIE()) {
//some logic
}
if(isSafari()) {
//some logic
}
```

**Comment by LaVa1804** [comment]
@vefimofff 
Added pull request "Removed redundant IE/Safari tricks", please check and merge if you see no issues there

**Comment by vefimofff** [comment]
Thanks @LaVa1804 for the fix!
