### ISSUE TITLE
Add overloaded constructor OurWaitFor accepting List<OurWebElement>

### ISSUE THREAD

**Issue by BlackEnf0rcer** [WileyLabs/teasy#36]
I using customCondition method for that, but it is deprecated.

**Comment by vefimofff** [comment]
@BlackEnf0rcer  could you please provide an example of customCondition usage? (the code will be the best) so I could see if it's possible to be replicated using current teasy approach or make necessary changes

**Comment by BlackEnf0rcer** [comment]
customCondition(webDriver ->
        {
            boolean result = getWolText().contains(oldText == null ? wolText : oldText);
            if (result == false) {
                this.getDriver().navigate().refresh();
            }
            return result;
        }, 
    private String getWolText() {
        List<OurWebElement> elementList = elements(By.xpath("//*[@id=\"searchResultsList\"]/ol/li/div[2]/p"));
        return elementList.get(0).getText() + " " + elementList.get(1).getText();
    }

**Comment by vefimofff** [comment]
@BlackEnf0rcer thanks, we will see what can be done. So far the only way to do this would look something like this

        element(By.id("")).waitFor().customCondition(webDriver -> {
            boolean result;
            if (result == false) {
                this.getDriver().navigate().refresh();
            }
            return result;
        });
        
This part -   element(By.id("")).waitFor() looks very artificial and we will discuss the best way of removing it to make it look like (for example)

waitFor().customCondition(webDriver -> {
            boolean result;
            if (result == false) {
                this.getDriver().navigate().refresh();
            }
            return result;
        });

**Comment by BlackEnf0rcer** [comment]
Or it may be something like:
elements(By.id("")).waitFor().customCondition(elements-> {
result = check(elements);
        boolean result;
        if (result == false) {
            this.getDriver().navigate().refresh();
        }
        return result;
    });

**Comment by vefimofff** [comment]
yep, even better. Got it. By the way if you feel that you could implement a customCondition accepting any kind of param (not only a webdriver) - feel free to open a pull request (and we can discuss step by step plan in gitter chat). If you don't feel like doing it - it may take some time till we get to it ;)

**Comment by vefimofff** [comment]
I just checked... and it may require more deep refactoring then just adding a new method.. gonna look at it next week

**Comment by vefimofff** [comment]
fixed in 1.0.8-beta
@BlackEnf0rcer  you should be able to call

        waitFor().condition(elements -> elements.size()> 5, elements(By.id("test")));
