### ISSUE TITLE
Incorrect behavior of OurWebElement. elements with additional parameter OurSearchStrategy strategy

### ISSUE THREAD

**Issue by BlackEnf0rcer** [WileyLabs/teasy#39]
It's very confusing, that method elements without strategy parameter searching inside context, but with parameter - at whole page.
    public List<OurWebElement> elements(By by) {
        return this.contextFinder.visibleElements(by);
    }

    public List<OurWebElement> elements(By by, OurSearchStrategy strategy) {
        return this.customFinder(strategy).visibleElements(by);
    }

**Comment by vefimofff** [comment]
This is definitely a bug. Thanks for finding it out! Will fix it shortly as it's a critical one.

**Comment by vefimofff** [comment]
fixed by https://github.com/WileyLabs/teasy/pull/40

**Comment by vefimofff** [comment]
fixed in 1.0.6-beta
