### ISSUE TITLE
Add Safari Technology Preview support

### ISSUE THREAD

**Issue by iiddd** [WileyLabs/teasy#48]
As Safari Technology Preview is the last version of Safari with built-in driver, it would be very useful to add support for it (Safari 10 has a lot of problems with driver)

**Comment by vefimofff** [comment]
@LaVa1804 can you please take care of this? I know u have done the same recently

**Comment by LaVa1804** [comment]
@vefimofff  Please take a look at https://github.com/WileyLabs/teasy/pull/53

**Comment by vefimofff** [comment]
fixed in 1.0.8-beta
