### ISSUE TITLE
getOptions() method in Select class throws exception

### ISSUE THREAD

**Issue by LaVa1804** [WileyLabs/teasy#60]

**Comment by BlackEnf0rcer** [comment]
I also encountered this bug.

**Comment by vefimofff** [comment]
We found the cause of it and it will be fixed in the upcoming release.

**Comment by BlackEnf0rcer** [comment]
select.getWrappedWebElement().elements(By.cssSelector("option"));
do the work

**Comment by vefimofff** [comment]
@BlackEnf0rcer  yeah, thanks for the suggested workaround. getOptions will be fixed. The entire approach to custom elements will probably be reworked later to be more useful and flexible

**Comment by vefimofff** [comment]
Fixed in 1.0.9-beta.
