### ISSUE TITLE
getOptions() method returns something strange

### ISSUE THREAD

**Issue by BlackEnf0rcer** [WileyLabs/teasy#62]
getOptions method now working after fix 1.0.9. But it returns a collection of elements each of them containing all options. So getContentTypeSelectOptions().get(0).getText() returns all option values, but not the first.

**Comment by vefimofff** [comment]
Yet another call for me to add unit tests for fixes instead of just blindly modifying the code. Thanks for reporting, will take a look when I have time.
@BlackEnf0rcer the fastest way to fix is to submit a pull request. (this time with unit test ;))

**Comment by vefimofff** [comment]
fixed. will be released soon

**Comment by vefimofff** [comment]
https://github.com/WileyLabs/teasy/pull/63

**Comment by vefimofff** [comment]
fixed in 1.0.11-beta
