### ISSUE TITLE
Annotations @OurBefore... and @OurAfter... work only with public methods

### ISSUE THREAD

**Issue by SmallAd** [WileyLabs/teasy#65]
Configuration information annotations (OurBefore... and OurAfter)  work only with public methods. But TestNG configuration information annotations work with all methods.

**Comment by vefimofff** [comment]
https://github.com/WileyLabs/teasy/pull/66 pull request with the fix

**Comment by vefimofff** [comment]
fixed in https://github.com/WileyLabs/teasy/pull/67

**Comment by vefimofff** [comment]
implemented in 1.0.11-beta
