### ISSUE TITLE
Method element.element(s) return elements without context... again

### ISSUE THREAD

**Issue by BlackEnf0rcer** [WileyLabs/teasy#68]
Works at 1.0.8
Not works at 1.0.11-beta

**Comment by vefimofff** [comment]
Could you please specify what do you mean by "without context"?. More details may help to fix the problem faster

**Comment by BlackEnf0rcer** [comment]
Sure. Element.Element should search inside element (in my case row in table) not at whole page.

**Comment by vefimofff** [comment]
Thanks for the details, got it. Will check it today. Now all fixes will be with unit tests, so we hope to make releases more stable in future.

**Comment by vefimofff** [comment]
fixed in 1.0.12-beta
