### ISSUE TITLE
No such element exception on using "should().beAbsent();"

### ISSUE THREAD

**Issue by skopanirov** [WileyLabs/teasy#85]
No such element exception on using "should().beAbsent();" on element that does not exist on page.

**Comment by vefimofff** [comment]
package com.wiley.autotest.framework.tests.elements.model.DifferentTypes test has a                 .checkNonExistingElementShouldBeAbsent();
method that is supposed to cover such situation and it passes. If you could help modeling your situation (in html example) - I would be happy to make the should().beAbsent() more robust. But as of now I need more details about your particular case

**Comment by skopanirov** [comment]
I've rechecked this issue and seems it's ok.
