### ISSUE TITLE
Use soft asserts for lists.

### ISSUE THREAD

**Issue by Lao-Ax** [WileyLabs/teasy#93]
In a case when we need to check a list of elements for some condition, it would better to use soft assertion. It will provide more information.
Here is an example:

```
SoftAssert soft = new SoftAssert();
elements(by).forEach(element -> soft.assertFalse(
      element.getText().isEmpty()), 
      "Element " + element.getLocator() + " without a text.");
soft.assertAll();
```

Imagine, that the list has 100500 elements, and 50 of them have empty text. In that case, we will not fail on the first error, we will collect all of them.

It would be very cool to implement such feature in the framework.

**Comment by vefimofff** [comment]
done in 1.0.19 as elements().should().
