### ISSUE TITLE
Use TeasyElement for OurScreenshot class on constructor

### ISSUE THREAD

**Issue by aleklukashevich** [WileyLabs/teasy#99]
As for block concept we have faced issue when we have List of blocks, then the locator for this blocks are the same, so when we are taking screenshots - getting inccorect screenshot with all the lements in list instead just one. 
So would be nice to have this approach to pass element to OurScreenshot class.

**Comment by vefimofff** [comment]
fixed by https://github.com/WileyLabs/teasy/pull/100
